name: CI Tutorial

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - deploy

jobs:
  "run-jest-tests":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Delete data
        run: npx ts-node remove_db.ts "mongodb://127.0.0.1:27017/my_library_db"

      - name: Run Tests
        run: npm run test

      - name: Build data
        run: npx ts-node insert_sample_data.ts "mongodb://127.0.0.1:27017/my_library_db"
