name: Setup Sample Data

on:
  push:
    branches:
      - deploy

jobs:
  setup-sample-data:
    runs-on: cs5500-self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Remove existing database
        run: node remove_db.ts

      - name: Insert sample data into database
        run: node insert_sample_db.ts
