on:
  push:
    branches:
      - deploy

jobs:
  "setup-database":
    runs-on: Heathers-MacBook-Pro-3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
