name: Setup and Deploy

on:
  push:
    branches:
      - deploy

jobs:
  setup-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove Existing DB
        run: npx ts-node remove_db.ts

      - name: Insert Sample DB
        run: npx ts-node insert_sample_db.ts
