on:
  push:
    branches:
      - deploy

jobs:
  "setup-database":
    runs-on: cs5500-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
