name: Setup and Deploy

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  setup-and-deploy:
    runs-on: self-hosted  # or cs5500-self-hosted if that's how it's named on your runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove Existing DB
        run: npx ts-node scripts/remove_db.ts

      - name: Insert Sample DB
        run: npx ts-node scripts/insert_sample_db.ts
